name: queues

services:
  rabbitmq:
    container_name: queues-rabbitmq
    image: rabbitmq:4-management
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  redis:
    container_name: queues-redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
